name: r6s_MC
description: "a plugin for creating rainbow six siege in minecraft!"
version: 1.4
api-version: 1.16
main: me.R6SMC.plugin.Main
commands:
  test:
    usage: </command>
  start:
    usage: /<command>
    description: starts the game
  jointeamred:
    usage: </command>
    description: joins red team
  jointeamblue:
    usage: </command>
    description: joins blue team
  ability:
    usage: </command>
    description: gives ability obj
  attkoperator:
    usage: </command> [ash|capitao|finka]
    description: picks attack operator of users choice
  defoperator:
    usage: </command> [doc|rook|Aruni]
    description: picks defense operator of users choice
  override:
    usage: </command> [movement] [true|false]
    description: overrides a parameter to a given value
  showPageBlue:
    usage: </command/> [default|doc|rook|Aruni] [1|2|3]
  showPageRed:
    usage: </command/> [ash|capitao|finka] [1|2|3]
  tbcm-dc:
    usage: </command> [KEEPAMMO|TESTING] [true,false]
    description: a development command used for testing. (IN BETA)




